### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
Also, quick question, what did you base this project layout on? This is very similar to the AlamoFire layout.

**Comment by sxg** [comment]
Hey, thanks for the addition! I based the project layout partly on AlamoFire, but I modified it due to a bug between CocoaPods interfacing with Jazzy to generate CocoaDocs. AlamoFire had the same bug, so I [reported it there](https://github.com/Alamofire/Alamofire/issues/1025), and I think they modified their layout in the same way I did to avoid the bug.

**Comment by fulldecent** [comment]
Excelled, and thanks for the tip. I am considering to remodel the CocoaPods default template https://github.com/CocoaPods/pod-template off of AlamoFire and wanted to see if anyone else is doing it that way.

I am trying to reproduce your project layout, but I have trouble selecting the correct simulator: https://travis-ci.org/fulldecent/FDChessboardView/jobs/126552343

Please let me know if you have seen that problem before.

**Comment by sxg** [comment]
Hey, sorry for being MIA for a few days. I noticed your Travis build is working now. Do you still need help with that?

**Comment by fulldecent** [comment]
I never figured it out, but I did my build to work like AlamoFire if only targeting iOS 9.3. There is interest in the pod-template project to move towards to project layout we are using. In the future MANY more people may be setting up their projects like us!

**Comment by sxg** [comment]
That's awesome! At first I really wanted to use the default `pod lib create` template for ForecastIO, but it was surprisingly incompatible with CocoaDocs. Let me know if you need help with documentation or any coding. I'll keep an eye on that repo and see if I can contribute.

I took a quick glance at your project, and I believe part of the issue is that your deployment target is set to iOS 9.3, but your tests are compiling to older versions. Try setting your deployment target to iOS 8.0. For your iOS 9.3 test, you have an error with `@testable import FDChessboardView`. That might be a build dependency issue?

**Comment by fulldecent** [comment]
Awesome, thanks for all the help. I will get in touch with you after CocoaPods 1.0 final is released and we get most of the progress on the AlamoFire style template.

Me too, I always start with `pod lib create` and then bang my head on the wall relearning everything each time!

**Comment by fulldecent** [comment]
Hello, I pull everything I have into a pull request. If you would like to check it out or if you would like to get involved, please see https://github.com/CocoaPods/pod-template/pull/168 Thanks!

**Comment by fulldecent** [comment]
Hello @sxg there is a lot of progress in CocoaPods/pod-template#168 If you have some time could you please take a look and advise how we can improve this? If we get this right, MANY projects will start using this template because it is the default for CocoaPods.

**Pull request merged**
