### PR TITLE
Updates the repository for Swift 3 compatibility

### PR DESCRIPTION
**Pull request by AngeloStavrow**
Merging this into the correct branch per [original PR](https://github.com/sxg/ForecastIO/pull/23). 👍

### CODE REVIEW

**Comment by sxg** [comment]
Thanks so much! I'll be reviewing this over the weekend before I merge into the swift3 branch.

**Comment by AngeloStavrow** [comment]
Happy to help! I look forward to your comments, I'm a bit new to this. 😄

**Comment by sxg** [comment]
I updated the `.travis.yml` file to run the unit tests on TravisCI, and it looks like there are some issues with Nimble. [Here's a link to the unit test issues](https://travis-ci.org/sxg/ForecastIO/jobs/152106579). For some reason TravisCI is passing the whole build, but a lot of the individual unit tests are failing. It looks like a lot of little errors - do you mind taking a look at them?

**Comment by AngeloStavrow** [comment]
Sure! I'll have a look at some point this week—I'm not familiar with Nimble, so it may take me a little time to fix.

**Comment by sxg** [comment]
No worries. I'm taking a look at this too.

**Comment by sxg** [comment]
I tried making some fixes to Nimble for Swift 3 compatibility, but it looks like there are some ongoing issues that may or may not be easily fixable. I'm thinking it might be a good idea to migrate away from Nimble and just use XCTest. What do you think of that? There aren't too many unit tests, so it won't be that much work, and I'd be able to remove another dependency from the project so we can avoid future compatibility issues. If you have better luck than me with updating Nimble, then definitely let me know and we can stick to the original plan.

**Comment by sxg** [comment]
I actually went ahead and did the migration to XCTest from Nimble. It didn't look like Nimble would be an easy migration to Swift 3, and ForecastIO isn't really benefiting too much from Nimble anyway. It just makes the unit test syntax a bit more readable. I've incorporated all of our combined changes into the swift3 branch. I'm going to close this pull request, but let me know what you think of this!

**Comment by AngeloStavrow** [comment]
I think that makes sense—while testing is obviously important, I can't help but feel that there's also something to be said for having less dependencies to worry about (especially when you're working in a language that's evolving as quickly as Swift).

**Pull request closed without merging**
